live_config_reload = true

[font]
size = 13.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = """
lfcd
"""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002[/"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002T"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = """
:GoToFile
"""
